---
title: "About"
format: html
---

Brought to you by the [Tandy Center for Ocean Forecasting](https://www.bigelow.org/services/ocean-forecasting/) at [Bigelow Laboratory for Ocean Science](https://www.bigelow.org) and [Colby College](https://www.colby.edu/).

# Contacts

[Dr. Nick Record](mailto:nrecord@bigelow.org)

[Ben Tupper](mailto:btupper@bigelow.org)

Raising questions or issues: If you have a question, start a new "issue" on [the github issues tab](https://github.com/BigelowLab/ColbyForecasting/issues).  If a question has been posed by another, and you think you can help with the answer then please feel free to respond. 

# Website

We build the website using [quarto](https://quarto.org/) which is perfect from transforming [RMarkdown](https://rmarkdown.rstudio.com/ pages into a website with minimal investment. See this [wiki page](https://github.com/BigelowLab/ColbyForecasting/wiki/Quarto) if you would like to add your work to you own fork of the class repository.

# Acknowledgments

Our thanks to [Omi Johnson](https://github.com/oj713) and [Kyle Oliveira](https://github.com/kolive4) for very welcome guidance on using [Tidymodels](https://www.tidymodels.org/).

# Data sources

Our thanks to [OBIS](https://obis.org/) for assembling, curating and distributing a remarkable database of species occurences.


Our thanks to [Natural Earth](https://www.naturalearthdata.com/) for assembling, curating and distributing a remarkable database of geophysical features.


Our thanks to the contributors and authors of [Gulf of Maine 2050: Visioning Regional Resilience and Sustainability](https://online.ucpress.edu/elementa/collection/266/Special-Feature-Gulf-of-Maine-2050-Visioning) for making their work available.


Our thanks to hundreds of authors and contributors of [R packages](https://cran.r-project.org/web/packages/available_packages_by_name.html) who make their work freely available so that we may advance our own work.
